apiVersion: v1
kind: Service
metadata:
  name: sample-web-svc
  labels:
    app: sample-web
    stage: staging
  namespace: staging
spec:
  selector:
    app: sample-web-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

